# Generated by Django 5.0.6 on 2024-06-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
