# Generated by Django 5.0.6 on 2024-06-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0003_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='harmony_care',
        ),
    ]
