# Generated by Django 5.0.6 on 2024-06-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0004_rename_title_product_harmony_care'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shelf_life_days',
        ),
        migrations.AddField(
            model_name='product',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lifetime_in_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='nece gun omru var', null=True),
        ),
    ]
