# Generated by Django 5.0.6 on 2024-06-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0005_remove_product_shelf_life_days_product_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HarmonyCare',
            new_name='CosmeticCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='harmony_care',
            new_name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='expires_at',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
