# Generated by Django 5.0.6 on 2024-06-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0006_rename_harmonycare_cosmeticcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expires_at',
            new_name='expired_at',
        ),
    ]
