# Generated by Django 5.0.6 on 2024-06-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0007_rename_expires_at_product_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateTimeField(),
        ),
    ]
