# Generated by Django 5.0.6 on 2024-06-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0008_alter_product_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_at',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateField(),
        ),
    ]
