# Generated by Django 5.0.6 on 2024-06-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0010_alter_product_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_at',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lifetime_in_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How long is the expiration date?', null=True),
        ),
    ]
