# Generated by Django 5.0.6 on 2024-06-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0012_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%y/%m/%d/'),
        ),
    ]
