# Generated by Django 5.0.6 on 2024-06-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_care', '0013_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='car_advertisement',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skin_care.image'),
        ),
    ]
